from: "ubuntu"
tasks:
 - echo: "coucou"
 - include: "java.yml"
# - create_user:
#    name: "toto"
#    system: yes
 - Samousa:
 - copy:
    content: |
      I have no idea what
      I'm doing
    dest: "/tmp/caca.txt"
 - copy:
    src: "./bim.txt"
    dest: "/bam/boum/bim/txt"
 - get_url:
    url: "http://www.google.fr"
    dest: "toto"
 - file:
    path: "{{ item }}"
    state: directory
   with_items:
    - "bim"
    - "bamboum"
 - Chiotte:
 - package:
    name: "{{ item }}"
   with_items:
    - "toto"
    - "{{ ta_chatte }}"
    - "toto"
 - shell: |
    #!/bin/bash
    echo "This is the entrypoint, baby"
# - unzip_file:
#    strip: yes

execute:
  david_jinola:
  java:
    jar: "coucou"